#!/usr/bin/env bash
# Configure HAproxy load balancer

apt-get update && apt-get upgrade -y
apt-get install haproxy -y

echo "frontend balancer
	bind *:80
	default_backend servers
backend servers
	balance roundrobin
	server web-01 54.87.204.19:80
	server web-02 35.153.67.168:80
" > /etc/haproxy/haproxy.cfg

service haproxy restart
