#!/bin/bash
ls -A | sort -t. -k1.2,1nr -k2 | awk '
  {
    if (NR == 1) {
      if ($1 ~ /^\.\/[.]{1,2}$/) {
        print $1"," " "; next
      } else if ($1 ~ /\/$/) {
        print $1"," " "; next
      } else {
        print $1"," " "
      }
    } else {
      if ($1 ~ /^\.\/[.]{1,2}$/) {
        print $1"," " "; next
      } else if ($1 ~ /\/$/) {
        print $1"," " "; next
      } else {
        if (NR == NR_) {
          print $1
        } else {
          print $1"," " "
        }
      }
    }
  }
  END { print "" }
'
