#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and displays the data.
awk -F " " '{print $1 " " $9}' apache-access.log | sort | uniq -cd | sort -k 1nr | awk -F " " '{print "    " $1 " " $2 " " $3}'
